# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creport.proto\"I\n\x06Report\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0f\n\x07station\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65grees\x18\x03 \x01(\x01\x12\x0f\n\x07raining\x18\x04 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'report_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REPORT']._serialized_start=16
  _globals['_REPORT']._serialized_end=89
# @@protoc_insertion_point(module_scope)
